name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Lerna
        run: npm install -g lerna@3.22.1
      - name: Install packages
        run: lerna exec -- npm install
      - name: Run lint
        run: lerna exec -- npm run lint
      - name: Run tests
        run: lerna exec -- npm run test
      - name: Report Coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info